runtime: nodejs12

env_variables:
  ACCESSKEYID: AKIAWP4KZR2TF56UGXWZ
  ACCESSKEYSECRET: 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
  SERVICE_ID: VAd7b55d720ef9614ead781a1a1edb339d
  ACCOUNT_SID: AC9805054125a722ee73a457f18b4614cb
  AUTH_TOKEN: 35552f4f740c8f68ae4815f2cae3fbf3

  PUBLIC_VAPID_KEY: BFhBrj0u1nrI_eGZFK-yw0YGv4JWAie6pRe-vinFlksMTjxwGPTzXbPk1-HyEmtz3xVS025W2zHqiLoPR72ECdM
  PRIVATE_VAPID_KEY: rfJyEip_x4YJbujfoFDF6Djox8gXyqliF4Amdy9G-3o